// <auto-generated />
using System;
using Faith.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faith.API.Migrations
{
    [DbContext(typeof(FaithDbContext))]
    [Migration("20220819122840_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Faith.API.Entities.Begeleider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Begeleiders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arne Verdcourt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tim Verdcourt"
                        });
                });

            modelBuilder.Entity("Faith.API.Entities.Jongere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BegeleiderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jongeren");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BegeleiderId = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            BegeleiderId = 1,
                            Name = "John Doe the second"
                        },
                        new
                        {
                            Id = 3,
                            BegeleiderId = 1,
                            Name = "John Doe the third"
                        },
                        new
                        {
                            Id = 4,
                            BegeleiderId = 1,
                            Name = "John Doe the fourth"
                        },
                        new
                        {
                            Id = 5,
                            BegeleiderId = 2,
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = 6,
                            BegeleiderId = 2,
                            Name = "Jane Doe the second"
                        },
                        new
                        {
                            Id = 7,
                            BegeleiderId = 2,
                            Name = "Jane Doe the third"
                        },
                        new
                        {
                            Id = 8,
                            BegeleiderId = 2,
                            Name = "Jane Doe the fourth"
                        });
                });

            modelBuilder.Entity("Faith.API.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JongereId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "",
                            JongereId = 1,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9343)
                        },
                        new
                        {
                            Id = 2,
                            ImageURL = "",
                            JongereId = 1,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9395)
                        },
                        new
                        {
                            Id = 3,
                            ImageURL = "",
                            JongereId = 2,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9402)
                        },
                        new
                        {
                            Id = 4,
                            ImageURL = "",
                            JongereId = 3,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9408)
                        },
                        new
                        {
                            Id = 5,
                            ImageURL = "",
                            JongereId = 4,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9414)
                        },
                        new
                        {
                            Id = 6,
                            ImageURL = "",
                            JongereId = 4,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9421)
                        },
                        new
                        {
                            Id = 7,
                            ImageURL = "",
                            JongereId = 5,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9427)
                        },
                        new
                        {
                            Id = 8,
                            ImageURL = "",
                            JongereId = 6,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9455)
                        },
                        new
                        {
                            Id = 9,
                            ImageURL = "",
                            JongereId = 7,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9462)
                        },
                        new
                        {
                            Id = 10,
                            ImageURL = "",
                            JongereId = 8,
                            TimeStamp = new DateTime(2022, 8, 19, 14, 28, 40, 708, DateTimeKind.Local).AddTicks(9470)
                        });
                });

            modelBuilder.Entity("Faith.API.Entities.Reactie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reacties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Testing 1",
                            PostId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Testing 2",
                            PostId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Testing 3",
                            PostId = 2
                        },
                        new
                        {
                            Id = 4,
                            Content = "Testing 4",
                            PostId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "Testing 5",
                            PostId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
